<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FAP.Domain\FAP.Domain.csproj" />
    <ProjectReference Include="..\FAP.Foundation\FAP.Foundation.csproj" />
    <ProjectReference Include="..\FAP.GuestWeb\FAP.GuestWeb.csproj" />
    <ProjectReference Include="..\FAP.Network\FAP.Network.csproj" />
    <ProjectReference Include="..\FAP.Shared\FAP.Shared.csproj" />
  </ItemGroup>

</Project>