<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FAP.Domain\FAP.Domain.csproj" />
    <ProjectReference Include="..\FAP.Foundation\FAP.Foundation.csproj" />
    <ProjectReference Include="..\libs\HttpServer\HttpServer.csproj" />
  </ItemGroup>

</Project>