<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>FAP.Domain</RootNamespace>
    <AssemblyName>FAP.Domain</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    
    
    <PackageReference Include="System.Drawing.Common" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="EmitCompilerGeneratedFiles" />
    <CompilerVisibleProperty Include="CompilerGeneratedFilesOutputPath" />
  </ItemGroup>

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FAP.Foundation\FAP.Foundation.csproj" />
    <ProjectReference Include="..\FAP.Network\FAP.Network.csproj" />
    <ProjectReference Include="..\FAP.Shared\FAP.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Web.Resources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>