<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Fap.Presentation</RootNamespace>
    <AssemblyName>Fap.Presentation</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\folder-yellow.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="9.0.8" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FAP.Application\FAP.Application.csproj" />
    <ProjectReference Include="..\..\FAP.Domain\FAP.Domain.csproj" />
    <ProjectReference Include="..\..\FAP.Foundation\FAP.Foundation.csproj" />
    <ProjectReference Include="..\..\FAP.Network\FAP.Network.csproj" />
    <ProjectReference Include="..\..\libs\Odyssey\Odyssey.csproj" />
    <ProjectReference Include="..\..\libs\WpfApplicationFramework\WpfApplicationFramework\WpfApplicationFramework\WpfApplicationFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\**\*" />
  </ItemGroup>

  <ItemGroup>
    <!-- Ensure Web.Help is present in publish output -->
    <Content Include="Web.Help\**\*">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>

    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    
    <None Include="Web.Help\css\ie.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\css\print.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\css\screen.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\help.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\images\Chart Bar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\images\client.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\images\Cog.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\images\Drawer Closed.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\images\Folder Sync.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\images\Search.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web.Help\images\web.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>